language: ruby
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
before_script:
  - cp spec/db/database.yml{.example,}
  - mysql -e 'create database acts_as_geocodable_test;'
  - createdb acts_as_geocodable_test -U postgres
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
