language: ruby
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
env:
  - DB=mysql
  - DB=postgresql
before_script:
  - cp spec/db/database.yml{.example,}
  - mysql -e 'create database acts_as_geocodable_test;'
  - createdb acts_as_geocodable_test -U postgres
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
