language: ruby
branches:
  only:
    - master
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
env:
  global:
    secure: | # CODECLIMATE_REPO_TOKEN
      TvVATBVNhppiCRYfAAzmIfppeftAl6NchlJlPdNJGkeyoplftnr6GPFJHO1u
      Yj0nznR+8OsKU6Kv7u8n+S9c3PRIBY9pw13GEWqrB9Pa5U9QK3h1xGA/ioKn
      eb74qe+vux/blTpZ1/mHrIKGBX03RaW8fdvePeSXik3u5uKZzVg=
  matrix:
    - DB=mysql
    - DB=postgresql
before_script:
  - cp spec/db/database.yml{.example,}
  - mysql -e 'create database acts_as_geocodable_test;'
  - createdb acts_as_geocodable_test -U postgres
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
